### ISSUE TITLE
Language system doesnt works

### ISSUE THREAD

**Issue by MegalithOffical** [SonMooSans/discord-bot-dashboard-next#11]
I did everythink which is in Docs but it didnt worked 
![image](https://user-images.githubusercontent.com/74655120/224568036-f912b91c-0bac-40c4-8234-703ccb077bde.png)
![image](https://user-images.githubusercontent.com/74655120/224568040-440dddad-aefc-439e-bc47-9ed487648164.png)
![image](https://user-images.githubusercontent.com/74655120/224568048-719d1c95-7af3-4bb7-a4b6-185b00f9992f.png)

**Comment by SonMooSans** [comment]
You need to update the next.js configuration

**Comment by MegalithOffical** [comment]
also can i make the backend api with express.js ?

**Comment by SonMooSans** [comment]
> also can i make the backend api with express.js?

Nest.js actually uses express.js under the hood, there's definitely no problem to use express.js directly
Also, we have a list of required routes for your backend, you are able to write the backend in any programming language such as Go, Java, Rust or Javascript
