### ISSUE TITLE
Credit issue

### ISSUE THREAD

**Issue by MegalithOffical** [SonMooSans/discord-bot-dashboard-next#7]
Hello, can I use this dashboard with my custom additions and with MySQL? However, is it possible to use it without giving credit?

**Comment by MegalithOffical** [comment]
I realised it uses MongoDB but i can modify database codes to mysql

**Comment by SonMooSans** [comment]
It's a template repository, you are able to use it for commercial uses or any kind of purposes

**Comment by MegalithOffical** [comment]
Im doing my bot as Non profit ( i dont sell anythink) so it wont be a problem?

**Comment by MegalithOffical** [comment]
also how can i add my own language i add it but its keep saying "404 | This page could not be found."

**Comment by SonMooSans** [comment]
What did you mean by "add my own language"? I don't understand what you're asking about

If you mean localization (aka i18n), you should take a look at the implementation of the built-in hook
The hook is based on the [i18n](https://nextjs.org/docs/advanced-features/i18n-routing) feature provided by Next.js

**Comment by MegalithOffical** [comment]
Thank you i will check it asap

**Comment by MegalithOffical** [comment]
I did everythink which is in Docs but it didnt worked 
![image](https://user-images.githubusercontent.com/74655120/224568036-f912b91c-0bac-40c4-8234-703ccb077bde.png)
![image](https://user-images.githubusercontent.com/74655120/224568040-440dddad-aefc-439e-bc47-9ed487648164.png)
![image](https://user-images.githubusercontent.com/74655120/224568048-719d1c95-7af3-4bb7-a4b6-185b00f9992f.png)
